import Head from "next/head";
import Header from "@/components/header";
import Footer from "@/components/footer";
import useSWR from 'swr'

export default function Profile() {
  const fetcher = (...args) => fetch(...args).then(res => res.json())
  const { data, error, isLoading } = useSWR('/api/user/123', fetcher)
 
  if (error) return <div>failed to load</div>
  if (isLoading) return <div>loading...</div>
  
  return (
    <div>
      <Head>
        <title>{`Create Next App - Profile`}</title>
        <meta
          name="description"
          content={"Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      Profile
      <div>hello {data.name}!</div>
      <Footer />
    </div>
  );
}